[metadata]
name = "ModMenu"
author = "MrJeranimo"
description = "This mod adds a \"Mods\" menu tab to the Main Menu Bar at the top of the screen. Each mod using ModMenu will have a relative submenu in \"Mods\" they can use."
license_name = "MIT"
update_path = "https://spacedock.info/mod/4054/ModMenu/download/0.1.0"
id = 23025
