[metadata]
name = "Celestial Charter"
author = "MrJeranimo"
description = "This mod tracks each Vehicle's status and situation for each of the Celestials and displays in in a neat GUI."
license_name = "MIT"
update_path = "https://spacedock.info/mod/4046/Celestial%20Charter/download/0.3.3"
id = 23029
