[metadata]
name = "Custom Catastronaut Skins"
author = "Thoteus"
description = "6 different kittens based on my own past and current cats!"
license_name = "CC-BY"
update_path = "https://spacedock.info/mod/4062/Custom%20Catastronaut%20Skins/download/1.2"
