[mods]
7dc8cb4ed6c9d757670ac0a4 = "mods/Avionics"
3773258a6ef66ffc150ced95 = "mods/Celestial_Charter"
a6940bc8d7cfbf9fdf72a7aa = "mods/Celestial_Charter"
3d144be1eebff9efc0ef9a7e = "mods/Celestial_Charter"
9fe2ee94de7bbfef9a967000 = "mods/Celestial_Charter"
b4c00b5999ffce7b36d758a0 = "mods/Celestial_Charter"
5d37bcf21ffee76a19ddf654 = "mods/Celestial_Charter"
d185c547de79f8efa28c0348 = "mods/Celestial_Charter"
5edc20bbdcfff6fd8dc938fd = "mods/Celestial_Charter"
2630b12dfd2def4f3f0ceafb = "mods/Just_Munley"
76d718d5f3f77ffef4a0c386 = "mods/Kitten_Ears!"
67e3710effee57fd1c8ac269 = "mods/Kitten_Ears!"
f846bf0ede73f3be0fd3bbc1 = "mods/Kitten_Engineer_Redux"
6206b12fed796bcf01a500bc = "mods/KittenRemoteControl"
8c568e65ebe7f6ffad2b0cf7 = "mods/KittenRemoteControl"
7401336cfcaeb7dd4e18cef7 = "mods/KittenRemoteControl"
dad3a8f1ff0fc71f5404d977 = "mods/KSA_Discord_Rich_Presence"
32a33263fbfed26eb57637bb = "mods/KSA_Discord_Rich_Presence"
77410b937fadf2d5fc312f9e = "mods/KSA_Mod_Manager_(KSAMM)"
75251e7acfbd7ddeede3a48c = "mods/KSA_Mod_Manager_(KSAMM)"
a9df89eddd97bfe3ed766d3b = "mods/KSA_Mod_Manager_(KSAMM)"
f47c894ad4c6367f509d6f0c = "mods/KSA_Mod_Manager_(KSAMM)"
7414efe1fbeec7ff997f553a = "mods/KSA_Mod_Manager_(KSAMM)"
8d314df3ff3ff7ffcc9f9dca = "mods/KSA_Mod_Manager_(KSAMM)"
ff9db2e8ffc7bee33c4410a2 = "mods/KSP-Redux"
f2cdfa31dff6f9fe10472c16 = "mods/KSP-Redux"
bdaa51d1ffbf6fbf85b26e14 = "mods/ModMenu"
57dce865e2ffad6faaf25525 = "mods/ModMenu_ExampleMod"
3725cf01defe48fffbff93d6 = "mods/ONeil Cylinder"
5fd2a97cbdaffbef22714052 = "mods/Spaceplanes_(SSTO_LV)_[WIP]"
226f672bfdbff7fd30c5d86e = "mods/Spaceplanes_(SSTO_LV)_[WIP]"
62abf7deeffb1de304f42d59 = "mods/Spaceplanes_(SSTO_LV)_[WIP]"
4851549cfffc27f7c360a9ff = "mods/StellarAnalytics"
