[mods]
72ccc756279dfbdfc9792b7a = "mods/Avionics/v1.1.0/ksamm.toml"
60d78539dfdf7ce70ae6c373 = "mods/KSADiscordRichPresence/v0.1.0/ksamm.toml"
2feddd376beedff1eeead09 = "mods/ModMenu/0.1.0/ksamm.toml"
