[metadata]
name = "KSA Mod Manager (KSAMM)"
author = "Awsomgamr999"
description = "A tool to easily install mods after downloading them."
license_name = "MIT"
update_path = "https://spacedock.info/mod/4048/KSA%20Mod%20Manager%20(KSAMM)/download/0.1.6b"
