[metadata]
name = "Spaceplanes (SSTO_LV) [WIP]"
author = "UriahGnu"
description = "Adds a couple simple spaceplanes and parts"
license_name = "CC-BY-NC-SA"
update_path = "https://spacedock.info/mod/4037/Spaceplanes%20(SSTO/LV)%20%5BWIP%5D/download/0.3.2"
