[metadata]
name = "Gustav Holst's The Planets Orchestral Suite Soundtrack"
author = "Thoteus"
description = "Replaces the stock KSA soundtrack with two unique orchestral suites by the English composer Gustav Holst"
license_name = "CC-BY"
update_path = "https://spacedock.info/mod/4063/Gustav%20Holst's%20The%20Planets%20Orchestral%20Suite%20Soundtrack/download/1.2"
id = 23054
