[metadata]
name = "Alternate Reality Moonar System"
author = "Thoteus"
description = "A detailed custom system with 7 planets and 25 moon/dwarf planets to explore!"
license_name = "CC-BY"
update_path = "https://spacedock.info/mod/4061/Alternate%20Reality%20Moonar%20System/download/1.6"
