[metadata]
name = "Kitten Ears!"
author = "dandoesstuff"
description = "Kittens how they should've been smh"
license_name = "MIT"
update_path = "https://spacedock.info/mod/4039/Kitten%20Ears!/download/1.1"
