[metadata]
name = "KSA Discord Rich Presence"
author = "ratInSuit"
description = "Add discord rich presence when you boot up the game, so it shows you're playing KSA."
license_name = "GPL-3.0"
update_path = "https://spacedock.info/mod/4050/KSA%20Discord%20Rich%20Presence/download/v0.1.0"
id = 23018
