[metadata]
name = "Avionics"
author = "Dejvid"
description = "Adds flight instruments and aircraft autopilot"
license_name = "MIT"
update_path = "https://spacedock.info/mod/4057/Avionics/download/v1.2.0"
