[metadata]
name = "KSADiscordRichPresence"
author = "ratInSuit"
description = "It's a simple mod that currently just shows in discord that you have KSA open."
license_name = "GPL-3.0"
update_path = "https://spacedock.info/mod/4050/KSA%20Discord%20Rich%20Presence/download"
