[metadata]
name = "Kitten Engineer Redux"
author = "BarneyTheGod"
description = "[VERY EARLY ALPHA] Kitten Engineer Redux is a tools and utility mod for Kitten Space Agency that displays helpful information, as well as a suicide burn calculator, and a small automatic flight computer."
license_name = "MIT"
update_path = "https://spacedock.info/mod/4043/Kitten%20Engineer%20Redux/download/v0.3"
id = 22986
