[metadata]
name = "O'Neil Cylinder"
author = "Kepeca"
description = "A mod that adds the conceptualized ONeil Cylinder to KSA."
license_name = "MIT"
update_path = "https://spacedock.info/mod/4038/O'Neil%20Cylinder/download/0.1"
